# Generated by Django 3.2.8 on 2022-02-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cats',
            new_name='category',
        ),
    ]
